name: Android CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: Setup JFrog CLI
      uses: jfrog/setup-jfrog-cli@v3
      env:
        # JFrog platform url (for example: https://acme.jfrog.io)
        JF_URL: ${{ secrets.JF_URL }}
        
        # JFrog Platform access token
        JF_ACCESS_TOKEN: ${{ secrets.JF_ACCESS_TOKEN }}
    - name: set up JDK 11
      uses: actions/setup-java@v3
      with:
        java-version: '11'
        distribution: 'temurin'
        cache: gradle

    - uses: gradle/gradle-build-action@v2
      with:
        gradle-version: 6.9.4
    - name: Grant execute permission for gradlew
      run: chmod +x gradlew
    - name: Run Gradle build with JFrog CLI
      run: |
       # Ping the server
       jf gradlec --repo-resolve external-android-dev-virtual --repo-deploy external-android-dev-local
       jf gradle clean artifactoryPublish -b build.gradle --project external
    - name: Publish Build to RT
      run: |
        jf rt ping
        jf rt bce
        jf rt bag
        #Publish build-info
        jf rt bp --project external

    - name: Create Release Bundles
      run: |
        jf rbc --builds=json/builds-spec.json --signing-key=${{ secrets.Key }} test-android-app 1.0.2
        # Promote to Prod
        #jf rbp --signing-key=${{ secrets.Key }} --overwrite=true test-android-app 1.0.1 PROD
        
        sleep 30s

    - name: Distribute Release Bundles
      run: |
        
        # Distribute App to an Edge
        jf rbd --dist-rules=json/dist-rules.json --create-repo=true test-android-app 1.0.2

